name: chatwing
description: ChatWing - AI ÁÅ»úÖúÊÖ
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
